####################################################
#                                                  #
#   Documentation for Real PlacesWordPress Theme   #
#                                                  #
####################################################

site_name: Real Places Documentation
theme:
  language: 'en'
  name: 'material'
  palette:
    primary: 'green'
    accent: 'freen'

extra_css:
    - css/layout.css

extra:
  social:
    - type: 'facebook'
      link: 'https://www.facebook.com/InspiryThemes/'
    - type: 'twitter'
      link: 'https://twitter.com/InspiryThemes'

nav:
    - Introduction: index.md
    - Installation & Demo Import:
        - Installation & Activation: installation-and-activation.md
        - Import Demo Contents: import-demo-contents.md
    - Inspiry Real Estate Settings:
      - Price Format: price-format-settings.md
      - URL Slugs: url-slugs-settings.md
      - Social: social-icons.md
      - Google Maps: google-maps-setup.md
      - Google Maps Troubleshooting: google-maps-troubleshooting.md
      - Google reCAPTCHA: google-recaptcha-setup.md
    - Home & News Setup:
        - Create Home & News Pages: create-home-and-news-pages.md
        - Header - Theme Options: header-theme-options.md
        - Home - Image Banner or Google Map or Slider: home-banner-map-slider.md
        - Home - Layout: home-layout.md
        - Home - Properties: home-properties.md
        - Home - How It Works: home-how-it-works.md
        - Home - Featured Properties: home-featured-properties.md
        - Home - Partners: home-partners.md
        - Home - News: home-news.md
    - Properties Search:
      - Create Search Page: create-search-page.md
      - Configure Properties Search: configure-properties-search.md
    - Add Content:
      - Add News Post: adding-news-post.md
      - Add Agent: adding-agent.md
      - Add Property: adding-property.md
    - Properties Pages: properties-pages.md
    - Agents Page: agent-page.md
    - Gallery Pages: gallery-pages.md
    - Contact Page: contact-page.md
    - FAQs Page: faqs-page.md
    - Testimonials Page: testimonials-page.md
    - Member Pages:
      - Allow User Registration: user-registration-setup.md
      - Social Login: social-login.md
      - Favorites Page: favorites-page.md
      - Edit Profile Page: edit-profile.md
      - Submit Property Page: submit-property.md
      - My Properties Page: my-properties.md
    - Compare Properties: compare-properties.md
    - Widgets:
      - Properties Search: advance-search-widget.md
      - Featured Properties: featured-properties-widget.md
      - Mortgage Calculator: mortgage-calculator-widget.md
      - Social Icons: social-icons-widget.md
      - List Custom Taxonomy: custom-taxonomy-widget.md
    - Translation: translation.md
    - PayPal IPN Setup: paypal-ipn-setup.md
    - dsIDXpress IDX Plugin:
      - Installation & Basic Setup: dsidxpress-installation.md
      - Content Setup: dsidxpress-content-setup.md
    - WPML:
        - WPML Basic Setup: wpml-basic-setup.md
        - Home & News Page: wpml-home-news-page.md
        - WPML Menu Sync: wpml-menu-sync.md
        - String Translation: wpml-string-translation.md
        - Taxonomy Translation: wpml-taxonomy-translation.md
        - Slugs Translation: wpml-slugs-translation.md
        - Translate Property: wpml-translate-property.md
        - Property Search Page: wpml-property-search-page.md
    - Customize Theme:
      - Customize Styles: customize-styles.md
      - Hire Customization Services: hire-customization-services.md

# Change it to true before building (mkdocs build) for putting online.
# It should be false for themeforest package.
use_directory_urls: true

markdown_extensions:
  - admonition
  - codehilite
  - toc
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
     emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - meta
